
POST http://localhost:3002/StripePaymentIntent
Content-Type: application/json

{
    "customer": "cus_RNMkdIEQTKBlNC", 
    "amount": 5000,                     
    "currency": "usd"                 
}


# CUSTOMER ID: cus_RNMkdIEQTKBlNC