
# POST http://localhost:3002/StripeProduct/create-product
# Content-Type: application/json

# {
#     "name": "Product 1",
#     "description": "Product 1 description"
# }



# POST http://localhost:3002/StripePrices/create-price
# Content-Type: application/json

# {
#     "unit_amount": 1000,
#     "currency": "usd",
#     "product": "prod_RPE0HIJbw5bnub"
# }

# POST http://localhost:3002/StripeCheckoutSession/create-checkout-session
# Content-Type: application/json

# {
#     "customer": "cus_RNMkdIEQTKBlNC",
#     "line_items": [{
#     "price": "price_1QWPZ8P5cm5w1aGdcGS9yclj",
#     "quantity": 1
#     }],
#     "mode": "payment"
# }

# POST http://localhost:3002/StripePrices/create-price
# Content-Type: application/json

# {
#     "unit_amount": 5025,
#     "currency": "usd",
#     "product": "prod_RWHq5SCg7tLGgo"
# }
### Create Stripe Checkout Session
POST http://localhost:3002/StripeCheckoutSession/create-checkout-session
Content-Type: application/json

{
  "line_items": [
    {
      "price_data": {
        "currency": "gbp",
        "product_data": {
          "name": "Invoice Payment",
          "description": "Payment for Invoice #12345"
        },
        "unit_amount": 5000
      },
      "quantity": 1
    }
  ],
  "mode": "payment",
  "success_url": "http://localhost:3002/success",
  "cancel_url": "http://localhost:3002/cancel"
}




# invoice item id: ii_1QdPe1P5cm5w1aGdhyeXjBM1